mission09_bzp123/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using mission09_bzp123.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_bzp123.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Cart cart { get; set; }
        public PurchaseController(IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]

        public IActionResult Checkout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!!");

            }
            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }

        }
    }
}

mission09_bzp123/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mission09_bzp123.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mission09_bzp123/Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission09_bzp123.Infrastructure;
using mission09_bzp123.Models;

namespace mission09_bzp123.Pages
{
    public class ShopModel : PageModel
    {
        private IBookStoreRepository repo { get; set; }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }

        public ShopModel (IBookStoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }



        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl= returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x=> x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

mission09_bzp123/Pages/PurchaseCompleted.cshtml
@page
@model mission09_bzp123.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Thank you for your purchase! Your order is on the way!!</h2>
    <a class="btn btn primary" asp-controller="Home">Return Home</a>
</div>

mission09_bzp123/Pages/Shop.cshtml
@page
@model mission09_bzp123.Pages.ShopModel
@{
}

<h2> Your Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.cart.Items)
        {
           <tr>
               <td>@i.Book.Title</td>
               <td>@i.Quantity</td>
               <td>@i.Book.Price</td>
               <td>@(i.Quantity * i.Book.Price)</td>

               <td class="text-center">
                   <form method="post" asp-page-handler="Remove">
                       <input type="hidden" name="bookId" value="@i.Book.BookId" />
                       <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                       <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                   </form>
               </td>
           </tr> 
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" >Total:</td>
            @*I added a green border around the total using bootstrap*@
            <td class="border border-success border-3">@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Purchase" asp-action="Checkout" >Checkout</a>
</div>

mission09_bzp123/Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />

    <!--I made my own favicon using https://www.favicon.cc/ -->
    <link rel="icon" type="image/x-icon" href="~/img/favicon.ico" />
</head>

<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">BOOK STORE</span>
    </div>
    
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>