mission09_bzp123/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission09_bzp123.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_bzp123.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

mission09_bzp123/Components/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission09_bzp123.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission09_bzp123.Components
{
    public class GenresViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }

        public GenresViewComponent (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData?.Values["bookGenre"];

            var genres = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(genres);
        }
    }
}

mission09_bzp123/Views/Shared/PartialView.cshtml
@{  
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded  p-1">
        <h4>
            @Model.Title
            <span class="badge bg-primary rounded-pill" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">ISBN: @Model.Isbn</div>
    <div class="card-text p-1">Type: @Model.Classification</div>
    <div class="card-text p-1">Genre: @Model.Category</div>
    <div class="card-text p-1">Page Count: @Model.PageCount</div>

    <form method="post" asp-page="/Shop">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>
</div>

mission09_bzp123/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Book Store</title>

    <!--I made my own favicon using https://www.favicon.cc/ -->
    <link rel="icon" type="image/x-icon" href="~/img/favicon.ico" />
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />

    @*Font Awesome Link*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" 
          integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BOOKSTORE</div>
                <div class="col-6 text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            Welcome!
            <vc:genres></vc:genres>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>